### ISSUE TITLE
Design Issue: Programming Club?

### ISSUE THREAD

**Issue by keshashah** [nerdyvaishali/FOSS-Clubs-India#3]
Hi @vthakkar1994 , Some universities have a programming club in general, and not an active FOSS-club dedicated for it. Shall we put the list of Pro-clubs too or let it be an exclusive FOSS club list?

**Comment by v-thakkar** [comment]
Hi @keshashah. If the club is active in organizing FOSS related activities then we can definitely put it over here. [with the list of activities for the reference]

**Comment by v-thakkar** [comment]
@keshashah I am closing this issue. You can send a PR if you want to add any college/students club who has organized FOSS related activities. Thanks
