### ISSUE TITLE
Error 403 while sending PR

### ISSUE THREAD

**Issue by Rakhisharma** [nerdyvaishali/FOSS-Clubs-India#4]
@vthakkar1994  I am trying to send a pull request. I got this error: 
remote: Permission to vthakkar1994/FOSS-Clubs-India.git denied to Rakhisharma.
fatal: unable to access 'https://github.com/vthakkar1994/FOSS-Clubs-India.git/': The requested URL returned error: 403

Did little search on it. But didn't found anything helpful.  Why I am getting this error? Any idea?

**Comment by v-thakkar** [comment]
@Rakhisharma May be try this: http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

I am assuming that you are sending a PR from another branch.

**Comment by Rakhisharma** [comment]
yay, it helped. thanks :)
